Added Novu, OS Notification Infrastructure
DeepSourceCorp/good-first-issue pull request #533
Opened 2022-12-01 10:51 UTC by iampearceman

Just added a link to the Novu project. 

Here is a link to the issues page : https://github.com/novuhq/novu/issues

Thanks ♥️

#### ℹ️ Repository information

**The repository has**:

- [ ] At least three issues with the `good first issue` label.
- [ ] At least 10 contributors.
- [ ] Detailed setup instructions for the project.
- [ ] CONTRIBUTING.md
- [ ] Actively maintained.

2022-12-04 05:25 UTC, patel-aum approved these changes

2022-12-14 18:00 UTC, simran-2501 approved these changes

2022-12-14 18:12 UTC, patel-aum approved these changes

2022-12-21 16:25 UTC, lucavallin commented
Hey @iampearceman  ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

2022-12-25 10:44 UTC, withshubh requested changes
Please make the following change.

2022-12-25 10:44 UTC, withshubh commented on data/repositories.toml
>    'github.com/npm/cli',
```suggestion
  'github.com/Noovolari/leapp',
  'github.com/novuhq/novu',
  'github.com/npm/cli',
```

2025-06-20 13:38 UTC, closed without merging

2025-06-20 13:38 UTC, iampearceman commented
Old